name: 'React Docker S2I'
inputs:
  registry: {required: true}
  username: {required: true}
  password: {required: true}
  image-name: {required: true}
  tag: {required: false, default: 'latest'}
runs:
  using: 'composite'
  steps:
    - name: Login to Registry
      shell: bash
      run: |
        echo "${{ inputs.password }}" | docker login ${{ inputs.registry }} -u ${{ inputs.username }} --password-stdin

    - name: Build and Push
      shell: bash
      run: |
        IMAGE="${{ inputs.registry }}/${{ inputs.image-name }}:${{ inputs.tag }}"
        SHA_IMAGE="${{ inputs.registry }}/${{ inputs.image-name }}:${GITHUB_SHA}"
        cp ${{ github.action_path }}/Dockerfile.react ./React-Frontend/Dockerfile.react
        cp ./React-Frontend/nginx.conf ./React-Frontend/nginx.conf
        docker build -t $IMAGE -t $SHA_IMAGE \
          -f ./React-Frontend/Dockerfile.react \
          ./React-Frontend
        docker push $IMAGE
        docker push $SHA_IMAGE
