name: 'React Docker S2I'
inputs:
  registry: {required: true}
  username: {required: true}
  password: {required: true}
  image-name: {required: true}
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        docker build -t ${{ inputs.registry }}/${{ inputs.image-name }}:latest -f .github/actions/react-docker-s2i/Dockerfile.react .
        echo "${{ inputs.password }}" | docker login ${{ inputs.registry }} -u ${{ inputs.username }} --password-stdin
        docker push ${{ inputs.registry }}/${{ inputs.image-name }}:latest
